# Site settings
title: Sam Swanke
email: skswanke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sam Swanke is a computer science student as well as a web and software developer. 
  He is currently attending college at the University of Vermont. 
  He is also looking for an Internship for summer 2016.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://skswanke.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  skswanke

# Build settings
markdown: kramdown
highlighter: pygments
